# Generated by Django 4.1.1 on 2022-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=35)),
            ],
        ),
    ]
