# Generated by Django 4.1.1 on 2022-12-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
